# Generated by Django 3.2.24 on 2024-12-04 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
    ]
