# Generated by Django 3.2.24 on 2024-12-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
