# Generated by Django 3.2.24 on 2024-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('business_location', models.CharField(max_length=100)),
                ('busienss_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(max_length=50)),
                ('business_address', models.CharField(max_length=255)),
                ('expected_transaction_volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_reg_number', models.CharField(max_length=50)),
                ('cac_document', models.FileField(upload_to='kyc_documents/')),
                ('memorandum_and_article_association', models.FileField(upload_to='kyc_documents/')),
                ('proof_of_address', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('share_ownership', models.CharField(choices=[('director', 'Director'), ('ceo', 'CEO')], max_length=100)),
                ('Bvn', models.CharField(max_length=11)),
                ('home_address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('government_id', models.CharField(choices=[('voters card', 'Voters card'), ('drivers license', 'Drivers license'), ('international passport', 'International Passport'), ('national id', 'National id')], max_length=100)),
                ('government_id_number', models.CharField(max_length=100)),
                ('upload_id', models.FileField(upload_to='kyc_documents/')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_business_details', models.BooleanField(default=False)),
                ('completed_business_documents', models.BooleanField(default=False)),
                ('completed_bank_account', models.BooleanField(default=False)),
                ('completed_business_owner', models.BooleanField(default=False)),
            ],
        ),
    ]
