# Generated by Django 3.2.24 on 2024-11-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0003_alter_businessdocument_cac_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='merchant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
