# Generated by Django 3.2.24 on 2024-11-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_businessowner_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessowner',
            name='upload_id',
        ),
    ]
