# Generated by Django 3.2.24 on 2024-11-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_alter_businessowner_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessowner',
            old_name='Bvn',
            new_name='bvn',
        ),
    ]
