# Generated by Django 3.2.24 on 2024-11-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_rename_bvn_businessowner_bvn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessowner',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='businessowner',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
