# Generated by Django 3.2.24 on 2024-11-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_auto_20241127_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='businessdocument',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='businessowner',
            name='merchant',
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='kyc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='kyc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to='kyc.kyc'),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='kyc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='kyc.kyc'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
