# Generated by Django 3.2.24 on 2024-11-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0014_businessowner_encrypted_bvn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessowner',
            name='encrypted_bvn',
        ),
    ]
