# Generated by Django 3.2.24 on 2024-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0015_remove_businessowner_encrypted_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='bvn',
            field=models.CharField(max_length=255),
        ),
    ]
