# Generated by Django 3.2.24 on 2024-11-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0016_alter_businessowner_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='kyc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner', to='kyc.kyc'),
        ),
    ]
