# Generated by Django 3.2.24 on 2024-12-03 18:55

import cloudinary.models
from django.db import migrations
import utility.validator


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0017_alter_businessowner_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdocument',
            name='cac_document',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[utility.validator.validate_file_type], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='businessdocument',
            name='memorandum_and_article_association',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
