# Generated by Django 3.2.24 on 2024-12-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0018_auto_20241203_1055'),
        ('kyc', '0018_auto_20241203_1120'),
    ]

    operations = [
    ]
