# Generated by Django 3.2.24 on 2024-12-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0019_merge_0018_auto_20241203_1055_0018_auto_20241203_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
    ]
