# Generated by Django 3.2.24 on 2024-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0021_auto_20241205_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
